### PR TITLE
express router config in async context does not work properly

### PR DESCRIPTION
**Pull request by mdaugs**
The async init prevented proper configuration of the API endpoints.  
I assume this is related to async ressource handling.
I noticed the error, because redirection to OIDC provider and Azure was broken

### CODE REVIEW

**Comment by mdaugs** [comment]
I also added a small fix for cookie-session (related to this issue: https://github.com/jaredhanson/passport/issues/907)

**Review by ansibleguy76 — COMMENTED** [review]
tx for catching this.  evaluating now

**Comment by ansibleguy76** [comment]
I reworked it a little bit.. but kept the main concept

**Comment by ansibleguy76** [comment]
Can you test the changes ?  also on dockerhub pushed (beta)

**Pull request merged**
